theme: jekyll-theme-hacker
title: Regulad's Pain Train
name: Regulad's Pain Train

# Plugins
plugins:
  - github-pages

# Elements
show_downloads: false
show_description: true
google_analytics: G-YN9EE1LSN6
post_show_tags: false
post_show_author: true

# Sass/SCSS
sass:
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
