# SEO
title: Regulad's Webzone
author: regulad

# Jekyll
remote_theme: regulad/crust-tastic@v2.0

# Plugins
plugins:
  - github-pages
  - jekyll-redirect-from

# Elements
gtag: G-YN9EE1LSN6
gtranslate: true
github_info: true
navigation: subfolder
favicon: /assets/favicon
