# SEO
title: Regulad's Webzone
author: regulad

# Jekyll
remote_theme: regulad/crust-tastic@v3.1

# Plugins
plugins:
  - github-pages
  - jekyll-redirect-from

# crust-tastic
crust_tastic:
  favicon: /assets/favicon # Controls the favicon of the webpage. If you would like to use a custom path, substitute truthy/falsey with /path/to/favicon, otherwise it will use the root of the site.
  gtag: G-YN9EE1LSN6 # Controls site gtag
  header:
    title: true # Controls Title
    github_desc: true # Controls the GitHub description.
  footer:
    navigation: subfolder # See below.
    github_link: true # Controls the GitHub link at the bottom of the page.
    
    google_translate: true # Controls google translate
