remote_theme: regulad/hacker
title: Regulad's Pain Train
name: Regulad's Pain Train

# Plugins
plugins:
  - github-pages

# Elements
show_header: true
show_description: true
show_footer: true
google_analytics: G-YN9EE1LSN6
post_show_author: true
favicon: /assets/favicon

# Sass/SCSS
sass:
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]
  
