
title: Regulad's Webzone
name: Regulad's Pain Train
author: regulad

# Plugins
plugins:
  - github-pages

# Elements
gtag: G-YN9EE1LSN6
github_info: true
navigation: subfolder
favicon: /assets/favicon
